version: '3'
services:
  api:
    image: hackdenoel-go
    container_name: hackdenoel-go
    build:
      context: .
      dockerfile: ./api/dockerfile
    volumes:
      - ./src:/app/
    ports:
      - "8080:8080"
    depends_on:
     - mysql
    stdin_open: true
    tty: true

  mysql:
    image: hackdenoel-mysql
    container_name: hackdenoel-mysql
    build:
      context: .
      dockerfile: ./db/dockerfile
    hostname: mysql
    expose:
      - 3306:3306
    environment:
      LANG: C.UTF-8
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: noel-db
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    tty: True