version: '3'
services:
  api:
    image: hackdenoel-go
    container_name: hackdenoel-go
    build:
      context: .
      dockerfile: ./api/dockerfile
    working_dir: /app/
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - ./src:/app/
    ports:
      - "8080:8080"
    depends_on:
     - mysql

  mysql:
    image: hackdenoel-mysql
    container_name: hackdenoel-mysql
    build:
      context: .
      dockerfile: ./db/dockerfile
    expose:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=noel-db
    tty: True